### ISSUE TITLE
Basket bug

### ISSUE THREAD

**Issue by corentinthibaud** [qbtl/tousolidaires-symfony#13]
Est-ce que tu as modifié quelque chose dans la fonction pour ajouter un produit au panier? Il manque toute la partie traitement du formulaire (ça marchait hier, c'est chelou)

**Comment by qbtl** [comment]
J,ai rien modifié sur ce que tu as fais hier donc je comprends pas trop

**Comment by corentinthibaud** [comment]
[Help.zip](https://github.com/qbtl/tousolidaires-symfony/files/7070963/Help.zip)
Est-ce que tu peux essayer de voir l'erreur? Je ne veux pas les push pour tout break

**Comment by qbtl** [comment]
Je n'ai pas d'idée sur pourquoi il y a une erreur donc si tu veux on peut voir ça ensemble demain ou dans la semaine

**Comment by qbtl** [comment]
Au passage, j'ai trouvé une solution pour la modification de la quantité d'un produit dans le panier sur la page basket
Regarde sur tousolidaires-symfony-tailwind dans BuyerController

**Comment by qbtl** [comment]
Sinon je n'ai plus d'erreur avec ton code donc ressayes de voir si ça marche même si je n'en suis pas sûr
